title: Your Name - Portfolio
email: your-email@example.com
description: Personal portfolio showcasing apps, workflows, and design projects
baseurl: ""
url: "https://brebeka-2025.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
